// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Annotation struct {
	ID          string  `json:"id"`
	DocumentID  string  `json:"document_id"`
	HighlightID *string `json:"highlight_id"`
	Exact       string  `json:"exact"`
	Prefix      string  `json:"prefix"`
	Suffix      string  `json:"suffix"`
	PosStart    int64   `json:"pos_start"`
	PosEnd      int64   `json:"pos_end"`
	Color       string  `json:"color"`
	Note        string  `json:"note"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	Rev         int64   `json:"rev"`
	DeletedAt   *string `json:"deleted_at"`
}

type AnnotationTag struct {
	ID           string  `json:"id"`
	AnnotationID string  `json:"annotation_id"`
	TagID        string  `json:"tag_id"`
	CreatedAt    string  `json:"created_at"`
	Rev          int64   `json:"rev"`
	DeletedAt    *string `json:"deleted_at"`
}

type Device struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	TokenHash  string  `json:"token_hash"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
	Rev        int64   `json:"rev"`
	DeletedAt  *string `json:"deleted_at"`
	LastSeenAt *string `json:"last_seen_at"`
}

type Document struct {
	ID           string  `json:"id"`
	CanonicalUrl string  `json:"canonical_url"`
	Title        string  `json:"title"`
	Markdown     string  `json:"markdown"`
	FetchedAt    string  `json:"fetched_at"`
	Excerpt      string  `json:"excerpt"`
	HeroImageUrl string  `json:"hero_image_url"`
	Author       string  `json:"author"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	Rev          int64   `json:"rev"`
	DeletedAt    *string `json:"deleted_at"`
}

type DocumentTag struct {
	ID         string  `json:"id"`
	DocumentID string  `json:"document_id"`
	TagID      string  `json:"tag_id"`
	CreatedAt  string  `json:"created_at"`
	Rev        int64   `json:"rev"`
	DeletedAt  *string `json:"deleted_at"`
}

type Feed struct {
	ID           string  `json:"id"`
	Url          string  `json:"url"`
	Kind         string  `json:"kind"`
	Title        string  `json:"title"`
	Config       string  `json:"config"`
	LastPolledAt *string `json:"last_polled_at"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	Rev          int64   `json:"rev"`
	DeletedAt    *string `json:"deleted_at"`
}

type FeedItem struct {
	ID        string  `json:"id"`
	FeedID    string  `json:"feed_id"`
	Url       string  `json:"url"`
	Status    string  `json:"status"`
	SeenAt    string  `json:"seen_at"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

type Highlight struct {
	ID            string  `json:"id"`
	DocumentID    string  `json:"document_id"`
	PipelineRunID string  `json:"pipeline_run_id"`
	Kind          string  `json:"kind"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	Metadata      string  `json:"metadata"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	Rev           int64   `json:"rev"`
	DeletedAt     *string `json:"deleted_at"`
}

type Job struct {
	ID        string  `json:"id"`
	Kind      string  `json:"kind"`
	Payload   string  `json:"payload"`
	Status    string  `json:"status"`
	Attempts  int64   `json:"attempts"`
	RunAfter  string  `json:"run_after"`
	LastError string  `json:"last_error"`
	Result    string  `json:"result"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

type MediaAsset struct {
	ID          string  `json:"id"`
	DocumentID  string  `json:"document_id"`
	OriginalUrl string  `json:"original_url"`
	LocalPath   string  `json:"local_path"`
	Kind        string  `json:"kind"`
	Width       *int64  `json:"width"`
	Height      *int64  `json:"height"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	Rev         int64   `json:"rev"`
	DeletedAt   *string `json:"deleted_at"`
}

type PairCode struct {
	Code      string  `json:"code"`
	ExpiresAt string  `json:"expires_at"`
	UsedAt    *string `json:"used_at"`
}

type Pipeline struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Enabled   int64   `json:"enabled"`
	Trigger   string  `json:"trigger"`
	Filter    string  `json:"filter"`
	Steps     string  `json:"steps"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

type PipelineRun struct {
	ID         string  `json:"id"`
	PipelineID string  `json:"pipeline_id"`
	DocumentID string  `json:"document_id"`
	Status     string  `json:"status"`
	StepIndex  int64   `json:"step_index"`
	State      string  `json:"state"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
	Rev        int64   `json:"rev"`
	DeletedAt  *string `json:"deleted_at"`
}

type ReadState struct {
	ID         string  `json:"id"`
	DeviceID   string  `json:"device_id"`
	DocumentID string  `json:"document_id"`
	ScrollY    float64 `json:"scroll_y"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
	Rev        int64   `json:"rev"`
	DeletedAt  *string `json:"deleted_at"`
}

type ServerSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Subscription struct {
	ID        string  `json:"id"`
	FeedID    string  `json:"feed_id"`
	IntervalH int64   `json:"interval_h"`
	NextRunAt string  `json:"next_run_at"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

type Tag struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Color     string  `json:"color"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}
