// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1, updated_at = ?
WHERE id = (
    SELECT j2.id FROM jobs j2
    WHERE j2.status = 'queued' AND j2.run_after <= ?
    ORDER BY j2.created_at
    LIMIT 1
)
RETURNING id, kind, payload, status, attempts, run_after, created_at, updated_at, rev, deleted_at
`

type ClaimNextJobParams struct {
	UpdatedAt string `json:"updated_at"`
	RunAfter  string `json:"run_after"`
}

func (q *Queries) ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, arg.UpdatedAt, arg.RunAfter)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at FROM devices
WHERE id = ? AND deleted_at IS NULL
`

type GetDeviceRow struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	TokenHash string  `json:"token_hash"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

func (q *Queries) GetDevice(ctx context.Context, id string) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at FROM devices
WHERE token_hash = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDocumentByCanonicalURL = `-- name: GetDocumentByCanonicalURL :one
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, created_at, updated_at, rev, deleted_at FROM documents WHERE canonical_url = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDocumentByCanonicalURL(ctx context.Context, canonicalUrl string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByCanonicalURL, canonicalUrl)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, created_at, updated_at, rev, deleted_at FROM documents WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaAssetByOriginalURL = `-- name: GetMediaAssetByOriginalURL :one
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE original_url = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMediaAssetByOriginalURL(ctx context.Context, originalUrl string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByOriginalURL, originalUrl)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getPairCode = `-- name: GetPairCode :one
SELECT code, expires_at, used_at FROM pair_codes WHERE code = ?
`

func (q *Queries) GetPairCode(ctx context.Context, code string) (PairCode, error) {
	row := q.db.QueryRowContext(ctx, getPairCode, code)
	var i PairCode
	err := row.Scan(&i.Code, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const getReadState = `-- name: GetReadState :one
SELECT id, device_id, document_id, scroll_y, created_at, updated_at, rev, deleted_at FROM read_states
WHERE device_id = ? AND document_id = ? AND deleted_at IS NULL LIMIT 1
`

type GetReadStateParams struct {
	DeviceID   string `json:"device_id"`
	DocumentID string `json:"document_id"`
}

func (q *Queries) GetReadState(ctx context.Context, arg GetReadStateParams) (ReadState, error) {
	row := q.db.QueryRowContext(ctx, getReadState, arg.DeviceID, arg.DocumentID)
	var i ReadState
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DocumentID,
		&i.ScrollY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM server_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (id, name, token_hash, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at
`

type InsertDeviceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Rev       int64  `json:"rev"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Rev,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, created_at, updated_at, rev, deleted_at
`

type InsertDocumentParams struct {
	ID           string `json:"id"`
	CanonicalUrl string `json:"canonical_url"`
	Title        string `json:"title"`
	Markdown     string `json:"markdown"`
	FetchedAt    string `json:"fetched_at"`
	Excerpt      string `json:"excerpt"`
	HeroImageUrl string `json:"hero_image_url"`
	Author       string `json:"author"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, insertDocument,
		arg.ID,
		arg.CanonicalUrl,
		arg.Title,
		arg.Markdown,
		arg.FetchedAt,
		arg.Excerpt,
		arg.HeroImageUrl,
		arg.Author,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, kind, payload, status, attempts, run_after, created_at, updated_at, rev)
VALUES (?, ?, ?, 'queued', 0, ?, ?, ?, 0)
RETURNING id, kind, payload, status, attempts, run_after, created_at, updated_at, rev, deleted_at
`

type InsertJobParams struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Payload   string `json:"payload"`
	RunAfter  string `json:"run_after"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.RunAfter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertMediaAsset = `-- name: InsertMediaAsset :one
INSERT INTO media_assets (id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at
`

type InsertMediaAssetParams struct {
	ID          string `json:"id"`
	DocumentID  string `json:"document_id"`
	OriginalUrl string `json:"original_url"`
	LocalPath   string `json:"local_path"`
	Kind        string `json:"kind"`
	Width       *int64 `json:"width"`
	Height      *int64 `json:"height"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) InsertMediaAsset(ctx context.Context, arg InsertMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, insertMediaAsset,
		arg.ID,
		arg.DocumentID,
		arg.OriginalUrl,
		arg.LocalPath,
		arg.Kind,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertPairCode = `-- name: InsertPairCode :exec
INSERT INTO pair_codes (code, expires_at) VALUES (?, ?)
`

type InsertPairCodeParams struct {
	Code      string `json:"code"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) InsertPairCode(ctx context.Context, arg InsertPairCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertPairCode, arg.Code, arg.ExpiresAt)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at FROM devices WHERE deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, created_at, updated_at, rev, deleted_at FROM documents WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalUrl,
			&i.Title,
			&i.Markdown,
			&i.FetchedAt,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAssetsByDocument = `-- name: ListMediaAssetsByDocument :many
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE document_id = ? AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListMediaAssetsByDocument(ctx context.Context, documentID string) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listMediaAssetsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.OriginalUrl,
			&i.LocalPath,
			&i.Kind,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE jobs SET status = 'done', updated_at = ? WHERE id = ?
`

type MarkJobDoneParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkJobDone(ctx context.Context, arg MarkJobDoneParams) error {
	_, err := q.db.ExecContext(ctx, markJobDone, arg.UpdatedAt, arg.ID)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs SET status = ?, attempts = ?, run_after = ?, updated_at = ? WHERE id = ?
`

type MarkJobFailedParams struct {
	Status    string `json:"status"`
	Attempts  int64  `json:"attempts"`
	RunAfter  string `json:"run_after"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobFailed,
		arg.Status,
		arg.Attempts,
		arg.RunAfter,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markPairCodeUsed = `-- name: MarkPairCodeUsed :exec
UPDATE pair_codes SET used_at = ? WHERE code = ?
`

type MarkPairCodeUsedParams struct {
	UsedAt *string `json:"used_at"`
	Code   string  `json:"code"`
}

func (q *Queries) MarkPairCodeUsed(ctx context.Context, arg MarkPairCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPairCodeUsed, arg.UsedAt, arg.Code)
	return err
}

const maxDeviceRev = `-- name: MaxDeviceRev :one
SELECT COALESCE(MAX(rev), 0) AS rev FROM devices
`

func (q *Queries) MaxDeviceRev(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxDeviceRev)
	var rev interface{}
	err := row.Scan(&rev)
	return rev, err
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices SET deleted_at = ?, updated_at = ?, rev = ?
WHERE id = ?
`

type SoftDeleteDeviceParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDevice,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.Rev,
		arg.ID,
	)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen_at = ? WHERE id = ?
`

type UpdateDeviceLastSeenParams struct {
	LastSeenAt *string `json:"last_seen_at"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastSeen, arg.LastSeenAt, arg.ID)
	return err
}

const updateDocumentExcerptHero = `-- name: UpdateDocumentExcerptHero :exec
UPDATE documents SET excerpt = ?, hero_image_url = ?, author = ?, updated_at = ? WHERE id = ?
`

type UpdateDocumentExcerptHeroParams struct {
	Excerpt      string `json:"excerpt"`
	HeroImageUrl string `json:"hero_image_url"`
	Author       string `json:"author"`
	UpdatedAt    string `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateDocumentExcerptHero(ctx context.Context, arg UpdateDocumentExcerptHeroParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentExcerptHero,
		arg.Excerpt,
		arg.HeroImageUrl,
		arg.Author,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertReadState = `-- name: UpsertReadState :one
INSERT INTO read_states (id, device_id, document_id, scroll_y, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(device_id, document_id) DO UPDATE SET
    scroll_y   = excluded.scroll_y,
    updated_at = excluded.updated_at,
    rev        = read_states.rev + 1
RETURNING id, device_id, document_id, scroll_y, created_at, updated_at, rev, deleted_at
`

type UpsertReadStateParams struct {
	ID         string  `json:"id"`
	DeviceID   string  `json:"device_id"`
	DocumentID string  `json:"document_id"`
	ScrollY    float64 `json:"scroll_y"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

func (q *Queries) UpsertReadState(ctx context.Context, arg UpsertReadStateParams) (ReadState, error) {
	row := q.db.QueryRowContext(ctx, upsertReadState,
		arg.ID,
		arg.DeviceID,
		arg.DocumentID,
		arg.ScrollY,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReadState
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DocumentID,
		&i.ScrollY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO server_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
