// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const bumpSubscriptionNextRun = `-- name: BumpSubscriptionNextRun :exec
UPDATE subscriptions SET next_run_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type BumpSubscriptionNextRunParams struct {
	NextRunAt string `json:"next_run_at"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) BumpSubscriptionNextRun(ctx context.Context, arg BumpSubscriptionNextRunParams) error {
	_, err := q.db.ExecContext(ctx, bumpSubscriptionNextRun, arg.NextRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1, updated_at = ?
WHERE id = (
    SELECT j2.id FROM jobs j2
    WHERE j2.status = 'queued' AND j2.run_after <= ?
    ORDER BY j2.created_at
    LIMIT 1
)
RETURNING id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id
`

type ClaimNextJobParams struct {
	UpdatedAt string `json:"updated_at"`
	RunAfter  string `json:"run_after"`
}

func (q *Queries) ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, arg.UpdatedAt, arg.RunAfter)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.ParentJobID,
	)
	return i, err
}

const clearCompletedJobs = `-- name: ClearCompletedJobs :execresult
UPDATE jobs SET deleted_at = ?, updated_at = ?
WHERE status IN ('done', 'dead', 'queued') AND deleted_at IS NULL
`

type ClearCompletedJobsParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) ClearCompletedJobs(ctx context.Context, arg ClearCompletedJobsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, clearCompletedJobs, arg.DeletedAt, arg.UpdatedAt)
}

const deleteAnnotationTag = `-- name: DeleteAnnotationTag :exec
UPDATE annotation_tags SET deleted_at = ?, rev = rev + 1
WHERE annotation_id = ? AND tag_id = ? AND deleted_at IS NULL
`

type DeleteAnnotationTagParams struct {
	DeletedAt    *string `json:"deleted_at"`
	AnnotationID string  `json:"annotation_id"`
	TagID        string  `json:"tag_id"`
}

func (q *Queries) DeleteAnnotationTag(ctx context.Context, arg DeleteAnnotationTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationTag, arg.DeletedAt, arg.AnnotationID, arg.TagID)
	return err
}

const deleteDocumentTag = `-- name: DeleteDocumentTag :exec
UPDATE document_tags SET deleted_at = ?, rev = rev + 1
WHERE document_id = ? AND tag_id = ? AND deleted_at IS NULL
`

type DeleteDocumentTagParams struct {
	DeletedAt  *string `json:"deleted_at"`
	DocumentID string  `json:"document_id"`
	TagID      string  `json:"tag_id"`
}

func (q *Queries) DeleteDocumentTag(ctx context.Context, arg DeleteDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentTag, arg.DeletedAt, arg.DocumentID, arg.TagID)
	return err
}

const deleteHighlightTag = `-- name: DeleteHighlightTag :exec
UPDATE highlight_tags SET deleted_at = ?, rev = rev + 1
WHERE highlight_id = ? AND tag_id = ? AND deleted_at IS NULL
`

type DeleteHighlightTagParams struct {
	DeletedAt   *string `json:"deleted_at"`
	HighlightID string  `json:"highlight_id"`
	TagID       string  `json:"tag_id"`
}

func (q *Queries) DeleteHighlightTag(ctx context.Context, arg DeleteHighlightTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteHighlightTag, arg.DeletedAt, arg.HighlightID, arg.TagID)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
UPDATE subscriptions SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type DeleteSubscriptionParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const getAnnotation = `-- name: GetAnnotation :one
SELECT id, document_id, highlight_id, exact, prefix, suffix, pos_start, pos_end, color, note, created_at, updated_at, rev, deleted_at FROM annotations WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAnnotation(ctx context.Context, id string) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, getAnnotation, id)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.HighlightID,
		&i.Exact,
		&i.Prefix,
		&i.Suffix,
		&i.PosStart,
		&i.PosEnd,
		&i.Color,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at FROM devices
WHERE id = ? AND deleted_at IS NULL
`

type GetDeviceRow struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	TokenHash string  `json:"token_hash"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	DeletedAt *string `json:"deleted_at"`
}

func (q *Queries) GetDevice(ctx context.Context, id string) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at FROM devices
WHERE token_hash = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDocumentByCanonicalURL = `-- name: GetDocumentByCanonicalURL :one
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, source_feed_id, created_at, updated_at, rev, deleted_at FROM documents WHERE canonical_url = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDocumentByCanonicalURL(ctx context.Context, canonicalUrl string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByCanonicalURL, canonicalUrl)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.SourceFeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, source_feed_id, created_at, updated_at, rev, deleted_at FROM documents WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.SourceFeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :one
SELECT id, url, kind, title, config, last_polled_at, created_at, updated_at, rev, deleted_at FROM feeds WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, id string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, url, kind, title, config, last_polled_at, created_at, updated_at, rev, deleted_at FROM feeds WHERE url = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getFeedItem = `-- name: GetFeedItem :one
SELECT id, feed_id, url, status, seen_at, created_at, updated_at, rev, deleted_at FROM feed_items WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetFeedItem(ctx context.Context, id string) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, getFeedItem, id)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Url,
		&i.Status,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id FROM jobs WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.ParentJobID,
	)
	return i, err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaAssetByOriginalURL = `-- name: GetMediaAssetByOriginalURL :one
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE original_url = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMediaAssetByOriginalURL(ctx context.Context, originalUrl string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByOriginalURL, originalUrl)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getPairCode = `-- name: GetPairCode :one
SELECT code, expires_at, used_at FROM pair_codes WHERE code = ?
`

func (q *Queries) GetPairCode(ctx context.Context, code string) (PairCode, error) {
	row := q.db.QueryRowContext(ctx, getPairCode, code)
	var i PairCode
	err := row.Scan(&i.Code, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, name, enabled, "trigger", "filter", steps, created_at, updated_at, rev, deleted_at FROM pipelines WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPipeline(ctx context.Context, id string) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipeline, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Trigger,
		&i.Filter,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, pipeline_id, document_id, status, step_index, state, created_at, updated_at, rev, deleted_at FROM pipeline_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetPipelineRun(ctx context.Context, id string) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.DocumentID,
		&i.Status,
		&i.StepIndex,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getPipelineRunByDocumentAndPipeline = `-- name: GetPipelineRunByDocumentAndPipeline :one
SELECT id, pipeline_id, document_id, status, step_index, state, created_at, updated_at, rev, deleted_at FROM pipeline_runs
WHERE document_id = ? AND pipeline_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT 1
`

type GetPipelineRunByDocumentAndPipelineParams struct {
	DocumentID string `json:"document_id"`
	PipelineID string `json:"pipeline_id"`
}

func (q *Queries) GetPipelineRunByDocumentAndPipeline(ctx context.Context, arg GetPipelineRunByDocumentAndPipelineParams) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRunByDocumentAndPipeline, arg.DocumentID, arg.PipelineID)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.DocumentID,
		&i.Status,
		&i.StepIndex,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getReadState = `-- name: GetReadState :one
SELECT id, device_id, document_id, scroll_y, created_at, updated_at, rev, deleted_at FROM read_states
WHERE device_id = ? AND document_id = ? AND deleted_at IS NULL LIMIT 1
`

type GetReadStateParams struct {
	DeviceID   string `json:"device_id"`
	DocumentID string `json:"document_id"`
}

func (q *Queries) GetReadState(ctx context.Context, arg GetReadStateParams) (ReadState, error) {
	row := q.db.QueryRowContext(ctx, getReadState, arg.DeviceID, arg.DocumentID)
	var i ReadState
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DocumentID,
		&i.ScrollY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM server_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, feed_id, interval_h, next_run_at, paused, created_at, updated_at, rev, deleted_at FROM subscriptions WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, id string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.IntervalH,
		&i.NextRunAt,
		&i.Paused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, created_at, updated_at, rev, deleted_at FROM tags WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, color, created_at, updated_at, rev, deleted_at FROM tags WHERE name = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertAnnotation = `-- name: InsertAnnotation :one
INSERT INTO annotations (id, document_id, highlight_id, exact, prefix, suffix, pos_start, pos_end, color, note, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING id, document_id, highlight_id, exact, prefix, suffix, pos_start, pos_end, color, note, created_at, updated_at, rev, deleted_at
`

type InsertAnnotationParams struct {
	ID          string  `json:"id"`
	DocumentID  string  `json:"document_id"`
	HighlightID *string `json:"highlight_id"`
	Exact       string  `json:"exact"`
	Prefix      string  `json:"prefix"`
	Suffix      string  `json:"suffix"`
	PosStart    int64   `json:"pos_start"`
	PosEnd      int64   `json:"pos_end"`
	Color       string  `json:"color"`
	Note        string  `json:"note"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) InsertAnnotation(ctx context.Context, arg InsertAnnotationParams) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, insertAnnotation,
		arg.ID,
		arg.DocumentID,
		arg.HighlightID,
		arg.Exact,
		arg.Prefix,
		arg.Suffix,
		arg.PosStart,
		arg.PosEnd,
		arg.Color,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.HighlightID,
		&i.Exact,
		&i.Prefix,
		&i.Suffix,
		&i.PosStart,
		&i.PosEnd,
		&i.Color,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertAnnotationTag = `-- name: InsertAnnotationTag :one
INSERT INTO annotation_tags (id, annotation_id, tag_id, created_at, rev)
VALUES (?, ?, ?, ?, 0)
RETURNING id, annotation_id, tag_id, created_at, rev, deleted_at
`

type InsertAnnotationTagParams struct {
	ID           string `json:"id"`
	AnnotationID string `json:"annotation_id"`
	TagID        string `json:"tag_id"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertAnnotationTag(ctx context.Context, arg InsertAnnotationTagParams) (AnnotationTag, error) {
	row := q.db.QueryRowContext(ctx, insertAnnotationTag,
		arg.ID,
		arg.AnnotationID,
		arg.TagID,
		arg.CreatedAt,
	)
	var i AnnotationTag
	err := row.Scan(
		&i.ID,
		&i.AnnotationID,
		&i.TagID,
		&i.CreatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (id, name, token_hash, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at
`

type InsertDeviceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Rev       int64  `json:"rev"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Rev,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertDocumentTag = `-- name: InsertDocumentTag :one
INSERT INTO document_tags (id, document_id, tag_id, created_at, rev)
VALUES (?, ?, ?, ?, 0)
RETURNING id, document_id, tag_id, created_at, rev, deleted_at
`

type InsertDocumentTagParams struct {
	ID         string `json:"id"`
	DocumentID string `json:"document_id"`
	TagID      string `json:"tag_id"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertDocumentTag(ctx context.Context, arg InsertDocumentTagParams) (DocumentTag, error) {
	row := q.db.QueryRowContext(ctx, insertDocumentTag,
		arg.ID,
		arg.DocumentID,
		arg.TagID,
		arg.CreatedAt,
	)
	var i DocumentTag
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TagID,
		&i.CreatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertHighlight = `-- name: InsertHighlight :one

INSERT INTO highlights (id, document_id, pipeline_run_id, kind, title, body, metadata, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING id, document_id, pipeline_run_id, kind, title, body, metadata, pinned, created_at, updated_at, rev, deleted_at
`

type InsertHighlightParams struct {
	ID            string `json:"id"`
	DocumentID    string `json:"document_id"`
	PipelineRunID string `json:"pipeline_run_id"`
	Kind          string `json:"kind"`
	Title         string `json:"title"`
	Body          string `json:"body"`
	Metadata      string `json:"metadata"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

// Highlights
func (q *Queries) InsertHighlight(ctx context.Context, arg InsertHighlightParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, insertHighlight,
		arg.ID,
		arg.DocumentID,
		arg.PipelineRunID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.PipelineRunID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Metadata,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertHighlightTag = `-- name: InsertHighlightTag :one
INSERT INTO highlight_tags (id, highlight_id, tag_id, created_at, rev)
VALUES (?, ?, ?, ?, 0)
RETURNING id, highlight_id, tag_id, created_at, rev, deleted_at
`

type InsertHighlightTagParams struct {
	ID          string `json:"id"`
	HighlightID string `json:"highlight_id"`
	TagID       string `json:"tag_id"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertHighlightTag(ctx context.Context, arg InsertHighlightTagParams) (HighlightTag, error) {
	row := q.db.QueryRowContext(ctx, insertHighlightTag,
		arg.ID,
		arg.HighlightID,
		arg.TagID,
		arg.CreatedAt,
	)
	var i HighlightTag
	err := row.Scan(
		&i.ID,
		&i.HighlightID,
		&i.TagID,
		&i.CreatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, kind, payload, status, attempts, run_after, created_at, updated_at, rev, parent_job_id)
VALUES (?, ?, ?, 'queued', 0, ?, ?, ?, 0, ?)
RETURNING id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id
`

type InsertJobParams struct {
	ID          string  `json:"id"`
	Kind        string  `json:"kind"`
	Payload     string  `json:"payload"`
	RunAfter    string  `json:"run_after"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	ParentJobID *string `json:"parent_job_id"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.RunAfter,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ParentJobID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
		&i.ParentJobID,
	)
	return i, err
}

const insertPairCode = `-- name: InsertPairCode :exec
INSERT INTO pair_codes (code, expires_at) VALUES (?, ?)
`

type InsertPairCodeParams struct {
	Code      string `json:"code"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) InsertPairCode(ctx context.Context, arg InsertPairCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertPairCode, arg.Code, arg.ExpiresAt)
	return err
}

const insertPipeline = `-- name: InsertPipeline :one

INSERT INTO pipelines (id, name, enabled, trigger, filter, steps, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING id, name, enabled, "trigger", "filter", steps, created_at, updated_at, rev, deleted_at
`

type InsertPipelineParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Enabled   int64  `json:"enabled"`
	Trigger   string `json:"trigger"`
	Filter    string `json:"filter"`
	Steps     string `json:"steps"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Pipelines
func (q *Queries) InsertPipeline(ctx context.Context, arg InsertPipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, insertPipeline,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Trigger,
		arg.Filter,
		arg.Steps,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Trigger,
		&i.Filter,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertPipelineRun = `-- name: InsertPipelineRun :one

INSERT INTO pipeline_runs (id, pipeline_id, document_id, status, step_index, state, created_at, updated_at, rev)
VALUES (?, ?, ?, 'queued', 0, '{}', ?, ?, 0)
RETURNING id, pipeline_id, document_id, status, step_index, state, created_at, updated_at, rev, deleted_at
`

type InsertPipelineRunParams struct {
	ID         string `json:"id"`
	PipelineID string `json:"pipeline_id"`
	DocumentID string `json:"document_id"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

// PipelineRuns
func (q *Queries) InsertPipelineRun(ctx context.Context, arg InsertPipelineRunParams) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, insertPipelineRun,
		arg.ID,
		arg.PipelineID,
		arg.DocumentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.DocumentID,
		&i.Status,
		&i.StepIndex,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO subscriptions (id, feed_id, interval_h, next_run_at, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, 0)
RETURNING id, feed_id, interval_h, next_run_at, paused, created_at, updated_at, rev, deleted_at
`

type InsertSubscriptionParams struct {
	ID        string `json:"id"`
	FeedID    string `json:"feed_id"`
	IntervalH int64  `json:"interval_h"`
	NextRunAt string `json:"next_run_at"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, insertSubscription,
		arg.ID,
		arg.FeedID,
		arg.IntervalH,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.IntervalH,
		&i.NextRunAt,
		&i.Paused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (id, name, color, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, 0)
RETURNING id, name, color, created_at, updated_at, rev, deleted_at
`

type InsertTagParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, insertTag,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const listAnnotationsByDocument = `-- name: ListAnnotationsByDocument :many
SELECT id, document_id, highlight_id, exact, prefix, suffix, pos_start, pos_end, color, note, created_at, updated_at, rev, deleted_at FROM annotations WHERE document_id = ? AND deleted_at IS NULL ORDER BY pos_start ASC
`

func (q *Queries) ListAnnotationsByDocument(ctx context.Context, documentID string) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.HighlightID,
			&i.Exact,
			&i.Prefix,
			&i.Suffix,
			&i.PosStart,
			&i.PosEnd,
			&i.Color,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsByTag = `-- name: ListAnnotationsByTag :many
SELECT a.id, a.document_id, a.highlight_id, a.exact, a.prefix, a.suffix, a.pos_start, a.pos_end, a.color, a.note, a.created_at, a.updated_at, a.rev, a.deleted_at FROM annotations a
JOIN annotation_tags at2 ON at2.annotation_id = a.id
WHERE at2.tag_id = ? AND at2.deleted_at IS NULL AND a.deleted_at IS NULL
ORDER BY a.created_at DESC
`

func (q *Queries) ListAnnotationsByTag(ctx context.Context, tagID string) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.HighlightID,
			&i.Exact,
			&i.Prefix,
			&i.Suffix,
			&i.PosStart,
			&i.PosEnd,
			&i.Color,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at, last_seen_at FROM devices WHERE deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, source_feed_id, created_at, updated_at, rev, deleted_at FROM documents WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalUrl,
			&i.Title,
			&i.Markdown,
			&i.FetchedAt,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Author,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTag = `-- name: ListDocumentsByTag :many
SELECT d.id, d.canonical_url, d.title, d.markdown, d.fetched_at, d.excerpt, d.hero_image_url, d.author, d.source_feed_id, d.created_at, d.updated_at, d.rev, d.deleted_at FROM documents d
JOIN document_tags dt ON dt.document_id = d.id
WHERE dt.tag_id = ? AND dt.deleted_at IS NULL AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
`

func (q *Queries) ListDocumentsByTag(ctx context.Context, tagID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalUrl,
			&i.Title,
			&i.Markdown,
			&i.FetchedAt,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Author,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsWithAnnotationCount = `-- name: ListDocumentsWithAnnotationCount :many
SELECT d.id, d.canonical_url, d.title, d.markdown, d.fetched_at, d.excerpt,
       d.hero_image_url, d.author, d.source_feed_id, d.created_at, d.updated_at,
       d.rev, d.deleted_at,
       COALESCE(COUNT(DISTINCT a.id), 0) AS annotation_count,
       COALESCE(COUNT(DISTINCT h.id), 0) AS highlight_count
FROM documents d
LEFT JOIN annotations a ON a.document_id = d.id AND a.deleted_at IS NULL
LEFT JOIN highlights h ON h.document_id = d.id AND h.deleted_at IS NULL
WHERE d.deleted_at IS NULL
GROUP BY d.id
ORDER BY d.created_at DESC
`

type ListDocumentsWithAnnotationCountRow struct {
	ID              string      `json:"id"`
	CanonicalUrl    string      `json:"canonical_url"`
	Title           string      `json:"title"`
	Markdown        string      `json:"markdown"`
	FetchedAt       string      `json:"fetched_at"`
	Excerpt         string      `json:"excerpt"`
	HeroImageUrl    string      `json:"hero_image_url"`
	Author          string      `json:"author"`
	SourceFeedID    *string     `json:"source_feed_id"`
	CreatedAt       string      `json:"created_at"`
	UpdatedAt       string      `json:"updated_at"`
	Rev             int64       `json:"rev"`
	DeletedAt       *string     `json:"deleted_at"`
	AnnotationCount interface{} `json:"annotation_count"`
	HighlightCount  interface{} `json:"highlight_count"`
}

func (q *Queries) ListDocumentsWithAnnotationCount(ctx context.Context) ([]ListDocumentsWithAnnotationCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsWithAnnotationCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsWithAnnotationCountRow
	for rows.Next() {
		var i ListDocumentsWithAnnotationCountRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalUrl,
			&i.Title,
			&i.Markdown,
			&i.FetchedAt,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Author,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.AnnotationCount,
			&i.HighlightCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT id, feed_id, interval_h, next_run_at, paused, created_at, updated_at, rev, deleted_at FROM subscriptions WHERE next_run_at <= ? AND deleted_at IS NULL AND paused = 0
`

func (q *Queries) ListDueSubscriptions(ctx context.Context, nextRunAt string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listDueSubscriptions, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.IntervalH,
			&i.NextRunAt,
			&i.Paused,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPipelines = `-- name: ListEnabledPipelines :many
SELECT id, name, enabled, "trigger", "filter", steps, created_at, updated_at, rev, deleted_at FROM pipelines WHERE enabled = 1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListEnabledPipelines(ctx context.Context) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Trigger,
			&i.Filter,
			&i.Steps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedItemsByFeed = `-- name: ListFeedItemsByFeed :many
SELECT id, feed_id, url, status, seen_at, created_at, updated_at, rev, deleted_at FROM feed_items WHERE feed_id = ? AND deleted_at IS NULL ORDER BY seen_at DESC
`

func (q *Queries) ListFeedItemsByFeed(ctx context.Context, feedID string) ([]FeedItem, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItemsByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedItem
	for rows.Next() {
		var i FeedItem
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Url,
			&i.Status,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, url, kind, title, config, last_polled_at, created_at, updated_at, rev, deleted_at FROM feeds WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Kind,
			&i.Title,
			&i.Config,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlights = `-- name: ListHighlights :many
SELECT id, document_id, pipeline_run_id, kind, title, body, metadata, pinned, created_at, updated_at, rev, deleted_at FROM highlights WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListHighlights(ctx context.Context, limit int64) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlights, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.PipelineRunID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByDocument = `-- name: ListHighlightsByDocument :many
SELECT id, document_id, pipeline_run_id, kind, title, body, metadata, pinned, created_at, updated_at, rev, deleted_at FROM highlights WHERE document_id = ? AND deleted_at IS NULL ORDER BY created_at ASC
`

func (q *Queries) ListHighlightsByDocument(ctx context.Context, documentID string) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.PipelineRunID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByPipelineRun = `-- name: ListHighlightsByPipelineRun :many
SELECT id, document_id, pipeline_run_id, kind, title, body, metadata, pinned, created_at, updated_at, rev, deleted_at FROM highlights WHERE pipeline_run_id = ? AND deleted_at IS NULL ORDER BY created_at ASC
`

func (q *Queries) ListHighlightsByPipelineRun(ctx context.Context, pipelineRunID string) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByPipelineRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.PipelineRunID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByTag = `-- name: ListHighlightsByTag :many
SELECT h.id, h.document_id, h.pipeline_run_id, h.kind, h.title, h.body, h.metadata, h.pinned, h.created_at, h.updated_at, h.rev, h.deleted_at FROM highlights h
JOIN highlight_tags ht ON ht.highlight_id = h.id
WHERE ht.tag_id = ? AND ht.deleted_at IS NULL AND h.deleted_at IS NULL
ORDER BY h.created_at DESC
`

func (q *Queries) ListHighlightsByTag(ctx context.Context, tagID string) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.PipelineRunID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id FROM jobs WHERE deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.ParentJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByKind = `-- name: ListJobsByKind :many
SELECT id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id FROM jobs WHERE kind = ? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100
`

func (q *Queries) ListJobsByKind(ctx context.Context, kind string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.ParentJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id FROM jobs WHERE status = ? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100
`

func (q *Queries) ListJobsByStatus(ctx context.Context, status string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.ParentJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatusAndKind = `-- name: ListJobsByStatusAndKind :many
SELECT id, kind, payload, status, attempts, run_after, last_error, result, created_at, updated_at, rev, deleted_at, parent_job_id FROM jobs WHERE status = ? AND kind = ? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100
`

type ListJobsByStatusAndKindParams struct {
	Status string `json:"status"`
	Kind   string `json:"kind"`
}

func (q *Queries) ListJobsByStatusAndKind(ctx context.Context, arg ListJobsByStatusAndKindParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatusAndKind, arg.Status, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.ParentJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAssetsByDocument = `-- name: ListMediaAssetsByDocument :many
SELECT id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at FROM media_assets WHERE document_id = ? AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListMediaAssetsByDocument(ctx context.Context, documentID string) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listMediaAssetsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.OriginalUrl,
			&i.LocalPath,
			&i.Kind,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineRunsByDocument = `-- name: ListPipelineRunsByDocument :many
SELECT id, pipeline_id, document_id, status, step_index, state, created_at, updated_at, rev, deleted_at FROM pipeline_runs WHERE document_id = ? AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPipelineRunsByDocument(ctx context.Context, documentID string) ([]PipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, listPipelineRunsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRun
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.DocumentID,
			&i.Status,
			&i.StepIndex,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelines = `-- name: ListPipelines :many
SELECT id, name, enabled, "trigger", "filter", steps, created_at, updated_at, rev, deleted_at FROM pipelines WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPipelines(ctx context.Context) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Trigger,
			&i.Filter,
			&i.Steps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, feed_id, interval_h, next_run_at, paused, created_at, updated_at, rev, deleted_at FROM subscriptions WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.IntervalH,
			&i.NextRunAt,
			&i.Paused,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByAnnotation = `-- name: ListTagsByAnnotation :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at, t.rev, t.deleted_at FROM tags t
JOIN annotation_tags at2 ON at2.tag_id = t.id
WHERE at2.annotation_id = ? AND at2.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByAnnotation(ctx context.Context, annotationID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByAnnotation, annotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByDocument = `-- name: ListTagsByDocument :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at, t.rev, t.deleted_at FROM tags t
JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = ? AND dt.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByDocument(ctx context.Context, documentID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByHighlight = `-- name: ListTagsByHighlight :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at, t.rev, t.deleted_at FROM tags t
JOIN highlight_tags ht ON ht.tag_id = t.id
WHERE ht.highlight_id = ? AND ht.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByHighlight(ctx context.Context, highlightID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByHighlight, highlightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCounts = `-- name: ListTagsWithCounts :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at, t.rev, t.deleted_at,
       COALESCE(SUM(CASE WHEN dt.id IS NOT NULL AND dt.deleted_at IS NULL THEN 1 ELSE 0 END), 0) AS doc_count,
       COALESCE(SUM(CASE WHEN at2.id IS NOT NULL AND at2.deleted_at IS NULL THEN 1 ELSE 0 END), 0) AS ann_count
FROM tags t
LEFT JOIN document_tags dt ON dt.tag_id = t.id
LEFT JOIN annotation_tags at2 ON at2.tag_id = t.id
WHERE t.deleted_at IS NULL
GROUP BY t.id
ORDER BY (COALESCE(SUM(CASE WHEN dt.deleted_at IS NULL THEN 1 ELSE 0 END), 0) + COALESCE(SUM(CASE WHEN at2.deleted_at IS NULL THEN 1 ELSE 0 END), 0)) DESC, t.name ASC
`

type ListTagsWithCountsRow struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	CreatedAt string      `json:"created_at"`
	UpdatedAt string      `json:"updated_at"`
	Rev       int64       `json:"rev"`
	DeletedAt *string     `json:"deleted_at"`
	DocCount  interface{} `json:"doc_count"`
	AnnCount  interface{} `json:"ann_count"`
}

func (q *Queries) ListTagsWithCounts(ctx context.Context) ([]ListTagsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithCountsRow
	for rows.Next() {
		var i ListTagsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
			&i.DocCount,
			&i.AnnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedPolled = `-- name: MarkFeedPolled :exec
UPDATE feeds SET last_polled_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type MarkFeedPolledParams struct {
	LastPolledAt *string `json:"last_polled_at"`
	UpdatedAt    string  `json:"updated_at"`
	ID           string  `json:"id"`
}

func (q *Queries) MarkFeedPolled(ctx context.Context, arg MarkFeedPolledParams) error {
	_, err := q.db.ExecContext(ctx, markFeedPolled, arg.LastPolledAt, arg.UpdatedAt, arg.ID)
	return err
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE jobs SET status = 'done', result = ?, updated_at = ? WHERE id = ?
`

type MarkJobDoneParams struct {
	Result    string `json:"result"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkJobDone(ctx context.Context, arg MarkJobDoneParams) error {
	_, err := q.db.ExecContext(ctx, markJobDone, arg.Result, arg.UpdatedAt, arg.ID)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs SET status = ?, attempts = ?, run_after = ?, updated_at = ? WHERE id = ?
`

type MarkJobFailedParams struct {
	Status    string `json:"status"`
	Attempts  int64  `json:"attempts"`
	RunAfter  string `json:"run_after"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobFailed,
		arg.Status,
		arg.Attempts,
		arg.RunAfter,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markJobLastError = `-- name: MarkJobLastError :exec
UPDATE jobs SET last_error = ?, updated_at = ? WHERE id = ?
`

type MarkJobLastErrorParams struct {
	LastError string `json:"last_error"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkJobLastError(ctx context.Context, arg MarkJobLastErrorParams) error {
	_, err := q.db.ExecContext(ctx, markJobLastError, arg.LastError, arg.UpdatedAt, arg.ID)
	return err
}

const markPairCodeUsed = `-- name: MarkPairCodeUsed :exec
UPDATE pair_codes SET used_at = ? WHERE code = ?
`

type MarkPairCodeUsedParams struct {
	UsedAt *string `json:"used_at"`
	Code   string  `json:"code"`
}

func (q *Queries) MarkPairCodeUsed(ctx context.Context, arg MarkPairCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPairCodeUsed, arg.UsedAt, arg.Code)
	return err
}

const maxDeviceRev = `-- name: MaxDeviceRev :one
SELECT COALESCE(MAX(rev), 0) AS rev FROM devices
`

func (q *Queries) MaxDeviceRev(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxDeviceRev)
	var rev interface{}
	err := row.Scan(&rev)
	return rev, err
}

const resetStuckJobs = `-- name: ResetStuckJobs :exec
UPDATE jobs SET status = 'queued', run_after = ?, updated_at = ?
WHERE status = 'running' AND updated_at < ? AND deleted_at IS NULL
`

type ResetStuckJobsParams struct {
	RunAfter    string `json:"run_after"`
	UpdatedAt   string `json:"updated_at"`
	UpdatedAt_2 string `json:"updated_at_2"`
}

// Reset jobs stuck in 'running' for longer than the given cutoff time back to 'queued'
// so the worker can retry them. Cutoff is an ISO8601 timestamp; jobs with updated_at
// older than that are considered stuck (crashed worker, lost context, hung HTTP call).
func (q *Queries) ResetStuckJobs(ctx context.Context, arg ResetStuckJobsParams) error {
	_, err := q.db.ExecContext(ctx, resetStuckJobs, arg.RunAfter, arg.UpdatedAt, arg.UpdatedAt_2)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET status = 'queued', attempts = 0, run_after = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type RetryJobParams struct {
	RunAfter  string `json:"run_after"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob, arg.RunAfter, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteAnnotation = `-- name: SoftDeleteAnnotation :exec
UPDATE annotations SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type SoftDeleteAnnotationParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteAnnotation(ctx context.Context, arg SoftDeleteAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAnnotation, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices SET deleted_at = ?, updated_at = ?, rev = ?
WHERE id = ?
`

type SoftDeleteDeviceParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	Rev       int64   `json:"rev"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDevice,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.Rev,
		arg.ID,
	)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteDocumentParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDocument, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteHighlight = `-- name: SoftDeleteHighlight :exec
UPDATE highlights SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type SoftDeleteHighlightParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteHighlight(ctx context.Context, arg SoftDeleteHighlightParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteHighlight, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteHighlightsByPipelineRun = `-- name: SoftDeleteHighlightsByPipelineRun :exec
UPDATE highlights SET deleted_at = ?, updated_at = ?, rev = rev + 1
WHERE pipeline_run_id = ? AND deleted_at IS NULL
`

type SoftDeleteHighlightsByPipelineRunParams struct {
	DeletedAt     *string `json:"deleted_at"`
	UpdatedAt     string  `json:"updated_at"`
	PipelineRunID string  `json:"pipeline_run_id"`
}

func (q *Queries) SoftDeleteHighlightsByPipelineRun(ctx context.Context, arg SoftDeleteHighlightsByPipelineRunParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteHighlightsByPipelineRun, arg.DeletedAt, arg.UpdatedAt, arg.PipelineRunID)
	return err
}

const softDeleteJob = `-- name: SoftDeleteJob :exec
UPDATE jobs SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type SoftDeleteJobParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteJob(ctx context.Context, arg SoftDeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteJob, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeletePipeline = `-- name: SoftDeletePipeline :exec
UPDATE pipelines SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type SoftDeletePipelineParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeletePipeline(ctx context.Context, arg SoftDeletePipelineParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePipeline, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeletePipelineRunsByDocument = `-- name: SoftDeletePipelineRunsByDocument :exec
UPDATE pipeline_runs SET deleted_at = ?, updated_at = ? WHERE document_id = ? AND deleted_at IS NULL
`

type SoftDeletePipelineRunsByDocumentParams struct {
	DeletedAt  *string `json:"deleted_at"`
	UpdatedAt  string  `json:"updated_at"`
	DocumentID string  `json:"document_id"`
}

func (q *Queries) SoftDeletePipelineRunsByDocument(ctx context.Context, arg SoftDeletePipelineRunsByDocumentParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePipelineRunsByDocument, arg.DeletedAt, arg.UpdatedAt, arg.DocumentID)
	return err
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags SET deleted_at = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type SoftDeleteTagParams struct {
	DeletedAt *string `json:"deleted_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTag, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateAnnotation = `-- name: UpdateAnnotation :exec
UPDATE annotations SET note = ?, color = ?, updated_at = ?, rev = rev + 1 WHERE id = ? AND deleted_at IS NULL
`

type UpdateAnnotationParams struct {
	Note      string `json:"note"`
	Color     string `json:"color"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, updateAnnotation,
		arg.Note,
		arg.Color,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen_at = ? WHERE id = ?
`

type UpdateDeviceLastSeenParams struct {
	LastSeenAt *string `json:"last_seen_at"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastSeen, arg.LastSeenAt, arg.ID)
	return err
}

const updateDocumentExcerptHero = `-- name: UpdateDocumentExcerptHero :exec
UPDATE documents SET excerpt = ?, hero_image_url = ?, author = ?, updated_at = ? WHERE id = ?
`

type UpdateDocumentExcerptHeroParams struct {
	Excerpt      string `json:"excerpt"`
	HeroImageUrl string `json:"hero_image_url"`
	Author       string `json:"author"`
	UpdatedAt    string `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateDocumentExcerptHero(ctx context.Context, arg UpdateDocumentExcerptHeroParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentExcerptHero,
		arg.Excerpt,
		arg.HeroImageUrl,
		arg.Author,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateFeedItemStatus = `-- name: UpdateFeedItemStatus :exec
UPDATE feed_items SET status = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type UpdateFeedItemStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateFeedItemStatus(ctx context.Context, arg UpdateFeedItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedItemStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateHighlightBody = `-- name: UpdateHighlightBody :exec
UPDATE highlights SET body = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type UpdateHighlightBodyParams struct {
	Body      string `json:"body"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateHighlightBody(ctx context.Context, arg UpdateHighlightBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateHighlightBody, arg.Body, arg.UpdatedAt, arg.ID)
	return err
}

const updateHighlightPinned = `-- name: UpdateHighlightPinned :exec
UPDATE highlights SET pinned = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type UpdateHighlightPinnedParams struct {
	Pinned    int64  `json:"pinned"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateHighlightPinned(ctx context.Context, arg UpdateHighlightPinnedParams) error {
	_, err := q.db.ExecContext(ctx, updateHighlightPinned, arg.Pinned, arg.UpdatedAt, arg.ID)
	return err
}

const updatePipeline = `-- name: UpdatePipeline :exec
UPDATE pipelines SET name = ?, enabled = ?, trigger = ?, filter = ?, steps = ?, updated_at = ?, rev = rev + 1
WHERE id = ?
`

type UpdatePipelineParams struct {
	Name      string `json:"name"`
	Enabled   int64  `json:"enabled"`
	Trigger   string `json:"trigger"`
	Filter    string `json:"filter"`
	Steps     string `json:"steps"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) error {
	_, err := q.db.ExecContext(ctx, updatePipeline,
		arg.Name,
		arg.Enabled,
		arg.Trigger,
		arg.Filter,
		arg.Steps,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePipelineRunProgress = `-- name: UpdatePipelineRunProgress :exec
UPDATE pipeline_runs SET status = ?, step_index = ?, state = ?, updated_at = ?, rev = rev + 1
WHERE id = ?
`

type UpdatePipelineRunProgressParams struct {
	Status    string `json:"status"`
	StepIndex int64  `json:"step_index"`
	State     string `json:"state"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePipelineRunProgress(ctx context.Context, arg UpdatePipelineRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunProgress,
		arg.Status,
		arg.StepIndex,
		arg.State,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSubscriptionPaused = `-- name: UpdateSubscriptionPaused :exec
UPDATE subscriptions SET paused = ?, updated_at = ?, rev = rev + 1 WHERE id = ?
`

type UpdateSubscriptionPausedParams struct {
	Paused    int64  `json:"paused"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSubscriptionPaused(ctx context.Context, arg UpdateSubscriptionPausedParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionPaused, arg.Paused, arg.UpdatedAt, arg.ID)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, source_feed_id, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(canonical_url) DO UPDATE SET
  title          = excluded.title,
  markdown       = excluded.markdown,
  fetched_at     = excluded.fetched_at,
  excerpt        = excluded.excerpt,
  hero_image_url = excluded.hero_image_url,
  author         = excluded.author,
  source_feed_id = COALESCE(excluded.source_feed_id, documents.source_feed_id),
  updated_at     = excluded.updated_at,
  rev            = documents.rev + 1
RETURNING id, canonical_url, title, markdown, fetched_at, excerpt, hero_image_url, author, source_feed_id, created_at, updated_at, rev, deleted_at
`

type UpsertDocumentParams struct {
	ID           string  `json:"id"`
	CanonicalUrl string  `json:"canonical_url"`
	Title        string  `json:"title"`
	Markdown     string  `json:"markdown"`
	FetchedAt    string  `json:"fetched_at"`
	Excerpt      string  `json:"excerpt"`
	HeroImageUrl string  `json:"hero_image_url"`
	Author       string  `json:"author"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.ID,
		arg.CanonicalUrl,
		arg.Title,
		arg.Markdown,
		arg.FetchedAt,
		arg.Excerpt,
		arg.HeroImageUrl,
		arg.Author,
		arg.SourceFeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CanonicalUrl,
		&i.Title,
		&i.Markdown,
		&i.FetchedAt,
		&i.Excerpt,
		&i.HeroImageUrl,
		&i.Author,
		&i.SourceFeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds (id, url, kind, title, config, last_polled_at, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(url) DO UPDATE SET
  kind           = excluded.kind,
  title          = excluded.title,
  config         = excluded.config,
  updated_at     = excluded.updated_at,
  rev            = feeds.rev + 1
RETURNING id, url, kind, title, config, last_polled_at, created_at, updated_at, rev, deleted_at
`

type UpsertFeedParams struct {
	ID           string  `json:"id"`
	Url          string  `json:"url"`
	Kind         string  `json:"kind"`
	Title        string  `json:"title"`
	Config       string  `json:"config"`
	LastPolledAt *string `json:"last_polled_at"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed,
		arg.ID,
		arg.Url,
		arg.Kind,
		arg.Title,
		arg.Config,
		arg.LastPolledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertFeedItem = `-- name: UpsertFeedItem :one
INSERT INTO feed_items (id, feed_id, url, status, seen_at, created_at, updated_at, rev)
VALUES (?, ?, ?, 'pending', ?, ?, ?, 0)
ON CONFLICT(feed_id, url) DO UPDATE SET
  seen_at    = excluded.seen_at,
  updated_at = excluded.updated_at,
  rev        = feed_items.rev + 1
RETURNING id, feed_id, url, status, seen_at, created_at, updated_at, rev, deleted_at
`

type UpsertFeedItemParams struct {
	ID        string `json:"id"`
	FeedID    string `json:"feed_id"`
	Url       string `json:"url"`
	SeenAt    string `json:"seen_at"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertFeedItem(ctx context.Context, arg UpsertFeedItemParams) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, upsertFeedItem,
		arg.ID,
		arg.FeedID,
		arg.Url,
		arg.SeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Url,
		&i.Status,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertMediaAsset = `-- name: UpsertMediaAsset :one
INSERT INTO media_assets (id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(original_url) DO UPDATE SET
  document_id = excluded.document_id,
  local_path  = excluded.local_path,
  kind        = excluded.kind,
  width       = excluded.width,
  height      = excluded.height,
  updated_at  = excluded.updated_at,
  rev         = media_assets.rev + 1
RETURNING id, document_id, original_url, local_path, kind, width, height, created_at, updated_at, rev, deleted_at
`

type UpsertMediaAssetParams struct {
	ID          string `json:"id"`
	DocumentID  string `json:"document_id"`
	OriginalUrl string `json:"original_url"`
	LocalPath   string `json:"local_path"`
	Kind        string `json:"kind"`
	Width       *int64 `json:"width"`
	Height      *int64 `json:"height"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertMediaAsset(ctx context.Context, arg UpsertMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaAsset,
		arg.ID,
		arg.DocumentID,
		arg.OriginalUrl,
		arg.LocalPath,
		arg.Kind,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OriginalUrl,
		&i.LocalPath,
		&i.Kind,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertReadState = `-- name: UpsertReadState :one
INSERT INTO read_states (id, device_id, document_id, scroll_y, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(device_id, document_id) DO UPDATE SET
    scroll_y   = excluded.scroll_y,
    updated_at = excluded.updated_at,
    rev        = read_states.rev + 1
RETURNING id, device_id, document_id, scroll_y, created_at, updated_at, rev, deleted_at
`

type UpsertReadStateParams struct {
	ID         string  `json:"id"`
	DeviceID   string  `json:"device_id"`
	DocumentID string  `json:"document_id"`
	ScrollY    float64 `json:"scroll_y"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

func (q *Queries) UpsertReadState(ctx context.Context, arg UpsertReadStateParams) (ReadState, error) {
	row := q.db.QueryRowContext(ctx, upsertReadState,
		arg.ID,
		arg.DeviceID,
		arg.DocumentID,
		arg.ScrollY,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReadState
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DocumentID,
		&i.ScrollY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO server_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
