// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at FROM devices
WHERE token_hash = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const getPairCode = `-- name: GetPairCode :one
SELECT code, expires_at, used_at FROM pair_codes WHERE code = ?
`

func (q *Queries) GetPairCode(ctx context.Context, code string) (PairCode, error) {
	row := q.db.QueryRowContext(ctx, getPairCode, code)
	var i PairCode
	err := row.Scan(&i.Code, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM server_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (id, name, token_hash, created_at, updated_at, rev)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, token_hash, created_at, updated_at, rev, deleted_at
`

type InsertDeviceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Rev       int64  `json:"rev"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Rev,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rev,
		&i.DeletedAt,
	)
	return i, err
}

const insertPairCode = `-- name: InsertPairCode :exec
INSERT INTO pair_codes (code, expires_at) VALUES (?, ?)
`

type InsertPairCodeParams struct {
	Code      string `json:"code"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) InsertPairCode(ctx context.Context, arg InsertPairCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertPairCode, arg.Code, arg.ExpiresAt)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, token_hash, created_at, updated_at, rev, deleted_at FROM devices WHERE deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rev,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPairCodeUsed = `-- name: MarkPairCodeUsed :exec
UPDATE pair_codes SET used_at = ? WHERE code = ?
`

type MarkPairCodeUsedParams struct {
	UsedAt sql.NullString `json:"used_at"`
	Code   string         `json:"code"`
}

func (q *Queries) MarkPairCodeUsed(ctx context.Context, arg MarkPairCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPairCodeUsed, arg.UsedAt, arg.Code)
	return err
}

const maxDeviceRev = `-- name: MaxDeviceRev :one
SELECT COALESCE(MAX(rev), 0) AS rev FROM devices
`

func (q *Queries) MaxDeviceRev(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxDeviceRev)
	var rev interface{}
	err := row.Scan(&rev)
	return rev, err
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices SET deleted_at = ?, updated_at = ?, rev = ?
WHERE id = ?
`

type SoftDeleteDeviceParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	UpdatedAt string         `json:"updated_at"`
	Rev       int64          `json:"rev"`
	ID        string         `json:"id"`
}

func (q *Queries) SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDevice,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.Rev,
		arg.ID,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO server_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
